version: 0.0
os: linux
files:
  - source: /tier1-frontend/
    destination: /var/www/3tier-app/
  - source: /tier2-app/
    destination: /opt/tier2-app/
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root
