version: 0.0
os: linux
files:
  - source: /tier1-frontend/
    destination: /home/ec2-user/deployment/tier1-frontend/
    overwrite: true
  - source: /tier2-app/
    destination: /home/ec2-user/deployment/tier2-app/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/web_start.sh
      timeout: 60
      runas: root
    - location: scripts/app_start.sh
      timeout: 120
      runas: root
